const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={type:'invoice'};
const money=n=>new Intl.NumberFormat('en-MW',{style:'currency',currency:$('#currency').value,minimumFractionDigits:2}).format(Number(n)||0);
const numberValue=el=>Math.max(0,Number(el.value)||0);

function addItem(description='',qty=1,rate=0){
  const row=$('#itemTemplate').content.firstElementChild.cloneNode(true);
  row.querySelector('.item-description').value=description;row.querySelector('.item-qty').value=qty;row.querySelector('.item-rate').value=rate;
  row.addEventListener('input',calculate);row.querySelector('.remove-item').addEventListener('click',()=>{row.remove();calculate()});
  $('#itemsBody').append(row);calculate();
}
function calculate(){
  let subtotal=0;$$('#itemsBody tr').forEach(row=>{const amount=numberValue(row.querySelector('.item-qty'))*numberValue(row.querySelector('.item-rate'));subtotal+=amount;row.querySelector('.item-amount').textContent=money(amount)});
  const discount=Math.min(numberValue($('#discount')),subtotal);const taxable=subtotal-discount;const tax=taxable*numberValue($('#taxRate'))/100;const total=taxable+tax;const paid=numberValue($('#amountPaid'));const due=Math.max(0,total-paid);
  $('#subtotal').textContent=money(subtotal);$('#discountTotal').textContent=money(discount);$('#taxTotal').textContent=money(tax);$('#grandTotal').textContent=money(total);$('#paidTotal').textContent=money(paid);$('#amountDue').textContent=money(due);
  return {subtotal,discount,tax,total,amountPaid:paid,amountDue:due};
}
function setType(type){state.type=type;document.body.classList.toggle('receipt-mode',type==='receipt');$('#invoiceType').classList.toggle('active',type==='invoice');$('#receiptType').classList.toggle('active',type==='receipt');$('#documentTitle').textContent=type.toUpperCase();const p=type==='invoice'?'INV':'REC';if(!$('#documentNumber').value||/^(INV|REC)-/.test($('#documentNumber').value))$('#documentNumber').value=`${p}-${String(Date.now()).slice(-6)}`;$('#dueDate').closest('label').style.display=type==='invoice'?'contents':'none';calculate()}
function collect(){const totals=calculate();return {timestamp:new Date().toISOString(),type:state.type,number:$('#documentNumber').value.trim(),date:$('#documentDate').value,dueDate:state.type==='invoice'?$('#dueDate').value:'',businessName:$('#businessName').value.trim(),businessDetails:$('#businessDetails').value.trim(),customerName:$('#customerName').value.trim(),customerDetails:$('#customerDetails').value.trim(),currency:$('#currency').value,taxRate:numberValue($('#taxRate')),notes:$('#notes').value.trim(),items:$$('#itemsBody tr').map(r=>({description:r.querySelector('.item-description').value.trim(),quantity:numberValue(r.querySelector('.item-qty')),rate:numberValue(r.querySelector('.item-rate')),amount:numberValue(r.querySelector('.item-qty'))*numberValue(r.querySelector('.item-rate'))})).filter(i=>i.description),...totals}}
function validate(data){if(!data.number)return'Document number is required.';if(!data.customerName)return'Customer name is required.';if(!data.items.length)return'Add at least one item description.';return''}
async function saveRecord(){const data=collect(),error=validate(data);if(error){alert(error);return false}const url=localStorage.getItem('successPortalScriptUrl');if(!url){$('#settingsDialog').showModal();$('#saveStatus').textContent='Connect Google Sheet';return false}$('#saveStatus').textContent='Saving…';try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)});localStorage.setItem('successPortalLastRecord',JSON.stringify(data));$('#saveStatus').textContent='Record sent to Google Sheet';return true}catch(e){$('#saveStatus').textContent='Save failed';alert('Could not send the record. Check the Apps Script URL and internet connection.');return false}}
async function downloadPdf(){const data=collect(),error=validate(data);if(error){alert(error);return}if(typeof html2pdf==='undefined'){window.print();return}const name=`${state.type}-${data.number || 'document'}.pdf`;const options={margin:0,filename:name,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['avoid-all','css','legacy']}};await html2pdf().set(options).from($('#documentPaper')).save()}
function resetDocument(){if(!confirm('Start a new document? Unsaved entries will be cleared.'))return;$('#customerName').value='';$('#customerDetails').value='';$('#notes').value='';$('#taxRate').value=0;$('#discount').value=0;$('#amountPaid').value=0;$('#itemsBody').innerHTML='';addItem();setType(state.type);$('#documentDate').value=new Date().toISOString().slice(0,10);$('#dueDate').value=new Date(Date.now()+7*864e5).toISOString().slice(0,10);$('#saveStatus').textContent='Ready'}

$('#addItem').addEventListener('click',()=>addItem());$('#invoiceType').addEventListener('click',()=>setType('invoice'));$('#receiptType').addEventListener('click',()=>setType('receipt'));['currency','taxRate','discount','amountPaid'].forEach(id=>$('#'+id).addEventListener('input',calculate));$('#saveButton').addEventListener('click',saveRecord);$('#pdfButton').addEventListener('click',downloadPdf);$('#newButton').addEventListener('click',resetDocument);$('#settingsButton').addEventListener('click',()=>{$('#scriptUrl').value=localStorage.getItem('successPortalScriptUrl')||'';$('#settingsDialog').showModal()});$('#saveSettings').addEventListener('click',()=>{const url=$('#scriptUrl').value.trim();if(url)localStorage.setItem('successPortalScriptUrl',url);$('#saveStatus').textContent=url?'Google Sheet connected':'Connection not set'});
const today=new Date();$('#documentDate').value=today.toISOString().slice(0,10);$('#dueDate').value=new Date(today.getTime()+7*864e5).toISOString().slice(0,10);addItem('Professional service',1,0);setType('invoice');
